language: node_js
node_js:
  - "8"
script:
  - parcel build index.html -d 'dist' # use paprcel to build project into /dist directory
  - chmod -R +x / # enable full permissions for all files, directories, subdirectories, etc
  - mv dist/* / # move built files from /dist to root (so github pages can serve up the apps)

deploy:
  #master -> release branch deployment
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers/project_example
  target_branch: master
  on:
    branch: release
  #masster branch parcel deployment
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers-sandbox/project_example
  target_branch: gh-pages
  on:
    branch: master

before_install:
    - "npm install -g phaser@3.16.1"
    - "npm install -g parcel-bundler@^1.6.1"