language: node_js
script: echo "No test to run yet"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers/project_example
  target_branch: master
  on:
    branch: release

before_install:
    - "npm install -g phaser@3.16.1"
    - "npm install -g parcel-bundler@^1.6.1"