language: node_js
node_js:
  - "6"
script:
  - parcel build index.html -d dist
deploy:
  #master -> release branch deployment
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers/project_example
  target_branch: master
  on:
    branch: release
  #masster branch parcel deployment
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers-sandbox/project_example
  target_branch: gh-pages
  on:
    branch: master

before_install:
    - "npm install -g phaser@3.16.1"
    - "npm install -g parcel-bundler@^1.6.1"